name: ci
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SIWE_JWT_SECRET: "test-secret"
      NEXT_PUBLIC_DEV_MODE: "true"
      FUNCTIONS_BASE_URL: "http://localhost:5001/PROJECT_ID/us-central1/contentAgent"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install web deps
        working-directory: apps/web
        run: npm ci

      - name: Typecheck web
        working-directory: apps/web
        run: npm run typecheck

      - name: Build web
        working-directory: apps/web
        run: npm run build

      - name: Install api deps
        working-directory: apps/api
        run: npm ci

      - name: Typecheck api
        working-directory: apps/api
        run: npm run typecheck

      - name: Python tests (unit)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install pytest
        run: pip install pytest requests
      - name: Run unit tests
        working-directory: tests/unit
        run: pytest -q

      - name: Install Playwright
        working-directory: tests/e2e
        run: |
          npm init -y
          npm i -D @playwright/test
          npx playwright install --with-deps
      - name: E2E smoke
        working-directory: tests/e2e
        run: npx playwright test --reporter=dot
