name: deploy
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SIWE_JWT_SECRET: ${{ secrets.SIWE_PRIVATE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install web deps
        working-directory: apps/web
        run: npm ci

      - name: Build web
        working-directory: apps/web
        run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod"
          working-directory: apps/web
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

      - name: Install Firebase Tools
        run: npm i -g firebase-tools

      - name: Deploy Functions
        working-directory: functions/content_agent
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          SIWE_JWT_SECRET: ${{ secrets.SIWE_PRIVATE_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          npm ci
          firebase deploy --only functions:contentAgent --token "$FIREBASE_TOKEN"

      - name: Smoke Test Function
        run: |
          echo "Skipping real invocation for safety; add curl with JWT if desired."
